### ISSUE TITLE
Stateful watch history

### ISSUE THREAD

**Issue by hotheadhacker** [hotheadhacker/youtube-player#4]
feature request: can we also add localstorage utilisation that save current progress of video and if user comes next time the video player will start with last watched video and last watch seek progress?

**Comment by HOTHEAD01TH** [comment]
Great suggestion! I can use localStorage to save the last watched video and timestamp via the YouTube API, then retrieve this data to set the video’s seek position accordingly.

**Comment by HOTHEAD01TH** [comment]
enhanced the app by adding features to save and resume user progress. The video’s current playback position, selected video, search query, and playlist are now stored in localStorage. When users return, the app retrieves these saved items, allowing them to resume watching from their last position, reload their previous search query, and display the same playlist they were exploring.

**Comment by HOTHEAD01TH** [comment]
Enhanced the app by adding features to save and resume user progress. The video’s current playback position, selected video, search query, and playlist are now stored in localStorage. When users return, the app retrieves these saved items, allowing them to resume watching from their last position, reload their previous search query, and display the same playlist they were exploring.

**Comment by hotheadhacker** [comment]
Awesome 😎
